### ISSUE TITLE
state_dims involved in computation in UKF

### ISSUE THREAD

**Issue by Hello-Water** [ser94mor/sensor-fusion#24]
![图片](https://user-images.githubusercontent.com/30867133/84642290-d4b1cd00-af2e-11ea-8d01-75fa3f81159f.png)

hello,
Should this ‘state_dims’ be ‘AugmentedStateDims’?

**Comment by ser94mor** [comment]
Hello, @JackingW !

It is a template arguments and the `Weights()` function is used in several places in the code. At least once this function is used with augmented state dims (https://github.com/ser94mor/sensor-fusion/blob/master/src/filters/UnscentedKalmanFilter.hpp#L263), and once with ordinary state dims (https://github.com/ser94mor/sensor-fusion/blob/master/src/filters/UnscentedKalmanFilter.hpp#L396). So, the answer is no, it should not be augmented state dims.

**Comment by Hello-Water** [comment]
Thank you, @ser94mor !
I understand now, your code is so beautiful !

**Comment by ser94mor** [comment]
Thank you, @JackingW !
